Repository shadow/shadow, pull requests merged in 2020-11, with the labels that each got.

#1016 Tests: add Rust tests for randomness
  src/test/Cargo.toml
  src/test/random/CMakeLists.txt
  src/test/random/random.test.shadow.config.yaml
  src/test/random/test_random.c
  src/test/random/test_random.rs
Labels: Component: Testing

#1022 Fix deprecated 'add-path' workflow command
  .github/workflows/lint.yml
  .github/workflows/run_tests.yml
Labels: Component: Testing

#1023 Added warning about yum/dnf installing 32-bit libraries
  docs/1.1-Shadow.md
Labels: Component: Documentation

#1024 Minor documentation improvements (main branch)
  docs/1.1-Shadow.md
  docs/1.2-Shadow-with-Docker.md
Labels: Component: Documentation

#1019 Improved sendto() and recvfrom() support and added tests
  src/main/host/descriptor/socket.c
  src/main/host/descriptor/socket.h
  src/main/host/descriptor/tcp.c
  src/main/host/descriptor/udp.c
  src/main/host/network_interface.c
  src/main/host/syscall/socket.c
  src/test/Cargo.toml
  src/test/socket/CMakeLists.txt
  src/test/socket/sendto_recvfrom/CMakeLists.txt
  src/test/socket/sendto_recvfrom/sendto-recvfrom.shadow.config.xml
  src/test/socket/sendto_recvfrom/test_sendto_recvfrom.rs
  src/test/test_utils.rs
Labels: Component: Main, Component: Testing

#1001 Rewrite test/unistd in Rust
  src/test/Cargo.toml
  src/test/test_common.c
  src/test/test_utils.rs
  src/test/unistd/CMakeLists.txt
  src/test/unistd/test_unistd.c
  src/test/unistd/test_unistd.rs
  src/test/unistd/unistd.test.shadow.config.yaml
Labels: Component: Testing, Type: Maintenance

#1004 Preload/ptrace hybrid mode
  ci/container_scripts/test.sh
  src/main/CMakeLists.txt
  src/main/core/slave.c
  src/main/core/support/options.c
  src/main/core/support/options.h
  src/main/host/process.c
  src/main/host/shimipc.c
  src/main/host/shimipc.h
  src/main/host/thread_preload.c
  src/main/host/thread_ptrace.c
  src/main/host/thread_ptrace.h
  src/shim/binary_spinning_sem.cc
  src/shim/binary_spinning_sem.h
  src/shim/ipc.cc
  src/shim/ipc.h
  src/shim/preload_syscalls.c
  src/shim/shim.c
  src/shim/shim_event.c
  src/shim/shim_event.h
  src/shim/shim_logger.c
  src/support/logger/logger.c
  src/test/phold/CMakeLists.txt
Labels: Component: Main, Type: Enhancement

#1017 Use sem_trywait instead of separate atomic
  src/shim/binary_spinning_sem.cc
  src/shim/binary_spinning_sem.h
Labels: Component: Main, Component: Shim, Type: Maintenance

#1030 Improve physical address handling
  src/main/bindings/rust/wrapper.rs
  src/main/host/process.c
  src/main/host/syscall_types.h
Labels: Component: Main, Type: Enhancement

#1025 Tests: add Rust tests for poll
  src/test/Cargo.toml
  src/test/poll/CMakeLists.txt
  src/test/poll/poll.test.shadow.config.yaml
  src/test/poll/test_poll.c
  src/test/poll/test_poll.rs
Labels: Component: Testing, Type: Maintenance

#1021 Tests: add Rust tests for mmap
  src/test/Cargo.toml
  src/test/memory/CMakeLists.txt
  src/test/memory/mmap.test.shadow.config.yaml
  src/test/memory/test_mmap.c
  src/test/memory/test_mmap.rs
  src/test/test_utils.rs
Labels: Component: Testing, Type: Maintenance
