Repository shadow/shadow, pull requests merged in 2020-12, with the labels that each got.

#1044 Remove Vagrant and EC2 docs
  docs/0-Design-Overview.md
  docs/1-Installation-and-Setup.md
  docs/1.3-Shadow-with-Vagrant.md
  docs/1.4-Shadow-with-EC2.md
  docs/README.md
Labels: Component: Documentation, Priority: Low, Status: Accepted, Type: Maintenance

#1047 Prevent idle workers in the work stealing policy
  src/main/core/scheduler/scheduler.c
  src/main/core/scheduler/scheduler_policy_host_steal.c
Labels: Component: Main, Priority: Critical, Status: In Progress, Type: Bug

#1050 Merge master into dev
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/dependabot.yml
  docs/0-Design-Overview.md
  docs/1-Installation-and-Setup.md
  docs/1.3-Shadow-with-Vagrant.md
  docs/1.4-Shadow-with-EC2.md
  docs/README.md
  docs/maintainer-playbook.md
  docs/nsf-sponsorship.md
  src/main/core/scheduler/scheduler.c
  src/main/core/scheduler/scheduler_policy_host_steal.c
Labels: Type: Maintenance

#1052 Configure issue template with link to discussions
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: Type: Maintenance

#1056 Updated dependabot config to use the new GitHub label
  .github/dependabot.yml
Labels: Component: Build, Priority: Low, Status: Accepted, Type: Bug

#1053 Add build info into log file and version message
  CMakeLists.txt
  config.h.in
  setup
  src/main/core/main.c
Labels: Component: Build, Type: Maintenance

#1057 Merge master→dev
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/dependabot.yml
  CMakeLists.txt
  config.h.in
  setup
  src/main/CMakeLists.txt
  src/main/core/main.c
Labels: Type: Maintenance

#1058 Add support for socketpair syscall
  src/main/host/descriptor/channel.c
  src/main/host/descriptor/channel.h
  src/main/host/descriptor/descriptor_table.c
  src/main/host/descriptor/descriptor_types.h
  src/main/host/descriptor/transport.c
  src/main/host/syscall/socket.c
  src/main/host/syscall/socket.h
  src/main/host/syscall/uio.c
  src/main/host/syscall/unistd.c
  src/main/host/syscall_handler.c
  src/shim/preload_syscalls.c
  src/test/socket/socketpair/CMakeLists.txt
Labels: Component: Main, Type: Enhancement

#1062 Upgrade rand, rand_core, and rand_chacha crates
  src/main/Cargo.toml
Labels: Component: Build, Priority: Low, Status: Accepted, Type: Maintenance
