Repository shadow/shadow, pull requests merged in 2020-09, with the labels that each got.

#934 Ensure that shim is initialized before first wrapped syscall is made.
  src/shim/preload_syscalls.c
  src/shim/shim.c
  src/shim/shim.h
  src/test/clone/test_clone.c
Labels: Component: Shim, Priority: Medium, Status: Accepted, Type: Bug

#956 Added tests for the connect() call
  src/main/host/process.c
  src/main/host/syscall/socket.c
  src/test/Cargo.toml
  src/test/socket/CMakeLists.txt
  src/test/socket/connect/CMakeLists.txt
  src/test/socket/connect/connect.shadow.config.xml
  src/test/socket/connect/test_connect.rs
Labels: Component: Testing

#957 Updated CMake config for socket tests
  src/test/socket/accept/CMakeLists.txt
  src/test/socket/bind/CMakeLists.txt
  src/test/socket/getsockname/CMakeLists.txt
  src/test/socket/listen/CMakeLists.txt
  src/test/socket/socket/CMakeLists.txt
Labels: Component: Testing

#960 Restructured part of the socket API tests
  src/test/socket/accept/test_accept.rs
  src/test/socket/bind/test_bind.rs
  src/test/socket/connect/test_connect.rs
  src/test/socket/getsockname/test_getsockname.rs
  src/test/socket/listen/test_listen.rs
  src/test/test_utils.rs
Labels: Component: Testing

#967 Use valid sockaddr when testing invalid file descriptors
  src/test/socket/bind/test_bind.rs
  src/test/socket/connect/test_connect.rs
  src/test/socket/getsockname/test_getsockname.rs
Labels: Component: Testing

#969 Added tests for the getpeername() call
  src/test/Cargo.toml
  src/test/socket/CMakeLists.txt
  src/test/socket/getpeername/CMakeLists.txt
  src/test/socket/getpeername/getpeername.shadow.config.xml
  src/test/socket/getpeername/test_getpeername.rs
Labels: Component: Testing

#970 Added tests for the socketpair() call
  src/test/Cargo.toml
  src/test/socket/CMakeLists.txt
  src/test/socket/accept/test_accept.rs
  src/test/socket/bind/test_bind.rs
  src/test/socket/connect/test_connect.rs
  src/test/socket/getpeername/test_getpeername.rs
  src/test/socket/getsockname/test_getsockname.rs
  src/test/socket/listen/test_listen.rs
  src/test/socket/socketpair/CMakeLists.txt
  src/test/socket/socketpair/socketpair.shadow.config.xml
  src/test/socket/socketpair/test_socketpair.rs
  src/test/test_utils.rs
Labels: Component: Testing

#981 Improve rust build process
  .github/workflows/lint.yml
  src/Cargo.toml
  src/main/.cargo/config.toml
  src/main/CMakeLists.txt
  src/test/.cargo/config.toml
  src/test/CMakeLists.txt
Labels: Component: Build System

#988 Added a dependabot config
  .github/dependabot.yml
Labels: Component: Dependencies

#989 [main branch] Added a dependabot config for the dev branch
  .github/dependabot.yml
Labels: Component: Dependencies

#990 Revert "Added a dependabot config"
  .github/dependabot.yml
Labels: Component: Dependencies

#987 Memory manager clarity improvements
  src/main/Cargo.toml
  src/main/bindings/c/bindings.h
  src/main/host/memory_manager.rs
  src/main/host/syscall_types.rs
  src/main/host/thread.rs
  src/main/utility/syscall.rs
Labels: Component: Main, Type: Maintenance

#993 Updated the (c)bindgen version numbers for the CI
  .github/workflows/lint.yml
Labels: Component: Testing

#982 Syscall handler for futex
  src/main/CMakeLists.txt
  src/main/bindings/rust/wrapper.rs
  src/main/core/support/object_counter.c
  src/main/core/support/object_counter.h
  src/main/host/descriptor/channel.c
  src/main/host/descriptor/descriptor.c
  src/main/host/descriptor/descriptor.h
  src/main/host/descriptor/descriptor_listener.c
  src/main/host/descriptor/descriptor_listener.h
  src/main/host/descriptor/descriptor_types.h
  src/main/host/descriptor/epoll.c
  src/main/host/descriptor/file.c
  src/main/host/descriptor/socket.c
  src/main/host/descriptor/tcp.c
  src/main/host/descriptor/timer.c
  src/main/host/descriptor/udp.c
  src/main/host/futex.c
  src/main/host/futex.h
  src/main/host/futex_table.c
  src/main/host/futex_table.h
  src/main/host/host.c
  src/main/host/host.h
  src/main/host/process.c
  src/main/host/process.h
  src/main/host/status.h
  src/main/host/status_listener.c
  src/main/host/status_listener.h
  src/main/host/syscall/clone.c
  src/main/host/syscall/clone.h
  src/main/host/syscall/epoll.c
  src/main/host/syscall/futex.c
  src/main/host/syscall/futex.h
  src/main/host/syscall/protected.c
  src/main/host/syscall/socket.c
  src/main/host/syscall/time.c
  src/main/host/syscall/uio.c
  src/main/host/syscall/unistd.c
  src/main/host/syscall/unistd.h
  src/main/host/syscall_condition.c
  src/main/host/syscall_condition.h
  src/main/host/syscall_handler.c
  src/main/host/syscall_types.h
  src/main/host/thread_ptrace.c
  src/test/CMakeLists.txt
  src/test/futex/CMakeLists.txt
  src/test/futex/futex.test.shadow.config.xml
  src/test/futex/test_futex.c
  src/test/leakcheck.log
Labels: Component: Main, Priority: High, Type: Enhancement

#975 Added tests for the shutdown() call
  src/main/host/descriptor/channel.c
  src/main/host/descriptor/tcp.c
  src/main/host/descriptor/udp.c
  src/main/host/descriptor/udp.h
  src/main/host/syscall/socket.c
  src/main/host/syscall/unistd.c
  src/test/CMakeLists.txt
  src/test/Cargo.toml
  src/test/file/test_file.c
  src/test/shutdown/CMakeLists.txt
  src/test/shutdown/test_shutdown.c
  src/test/socket/CMakeLists.txt
  src/test/socket/accept/CMakeLists.txt
  src/test/socket/accept/test_accept.rs
  src/test/socket/bind/CMakeLists.txt
  src/test/socket/bind/test_bind.rs
  src/test/socket/connect/CMakeLists.txt
  src/test/socket/connect/test_connect.rs
  src/test/socket/getpeername/CMakeLists.txt
  src/test/socket/getpeername/test_getpeername.rs
  src/test/socket/getsockname/CMakeLists.txt
  src/test/socket/getsockname/test_getsockname.rs
  src/test/socket/listen/CMakeLists.txt
  src/test/socket/listen/test_listen.rs
  src/test/socket/shutdown/CMakeLists.txt
  src/test/socket/shutdown/shutdown.shadow.config.xml
  src/test/socket/shutdown/test_shutdown.rs
  src/test/socket/socket/CMakeLists.txt
  src/test/socket/socketpair/CMakeLists.txt
  src/test/socket/socketpair/test_socketpair.rs
  src/test/test_utils.rs
Labels: Component: Testing

#961 Clear the signal mask at startup
  src/main/core/main.c
Labels: Component: Main

#994 Added `set!` macro for tests
  src/test/socket/accept/test_accept.rs
  src/test/socket/bind/test_bind.rs
  src/test/socket/connect/test_connect.rs
  src/test/socket/getpeername/test_getpeername.rs
  src/test/socket/getsockname/test_getsockname.rs
  src/test/socket/listen/test_listen.rs
  src/test/socket/shutdown/test_shutdown.rs
  src/test/socket/socketpair/test_socketpair.rs
  src/test/test_utils.rs
Labels: Component: Testing
