Repository shadow/shadow, pull requests merged in 2021-02, with the labels that each got.

#1078 Improve getsockopt() and setsockopt() and add tests
  src/main/host/syscall/socket.c
  src/test/Cargo.toml
  src/test/socket/CMakeLists.txt
  src/test/socket/sockopt/CMakeLists.txt
  src/test/socket/sockopt/sockopt.shadow.config.yaml
  src/test/socket/sockopt/test_sockopt.rs
  src/test/test_utils.rs
Labels: Component: Testing, Type: Enhancement

#1079 Pinning main
  .github/workflows/build_shadow.yml
  src/main/CMakeLists.txt
  src/main/core/main.c
  src/main/core/support/options.c
  src/main/core/support/options.h
  src/main/core/worker.c
  src/main/core/worker.h
  src/main/host/affinity.c
  src/main/host/affinity.h
Labels: Component: Main, Type: Enhancement

#1082 Increase phold timeout to 90 to stop failing tests
  src/test/phold/CMakeLists.txt
Labels: Component: Testing, Type: Maintenance

#1081 Merge master→dev
  src/main/CMakeLists.txt
  src/main/core/main.c
  src/main/core/support/options.c
  src/main/core/support/options.h
  src/main/core/worker.c
  src/main/core/worker.h
  src/main/host/affinity.c
  src/main/host/affinity.h
Labels: Type: Maintenance

#1085 Add CARGO_TERM_COLOR=always to workflows
  .github/workflows/lint.yml
  .github/workflows/run_tests.yml
Labels: Component: Testing

#1086 Added some Rust wrappers around C types
  src/main/host/descriptor/mod.rs
  src/main/host/descriptor/pipe.rs
  src/main/host/syscall/mod.rs
  src/main/host/syscall/unistd.rs
Labels: Component: Main

#1075 Miscellaneous syscalls to support running Tor
  src/main/CMakeLists.txt
  src/main/host/host.c
  src/main/host/host.h
  src/main/host/process.c
  src/main/host/process.h
  src/main/host/syscall/futex.c
  src/main/host/syscall/futex.h
  src/main/host/syscall/process.c
  src/main/host/syscall/process.h
  src/main/host/syscall/signal.c
  src/main/host/syscall/signal.h
  src/main/host/syscall/sysinfo.c
  src/main/host/syscall/sysinfo.h
  src/main/host/syscall_handler.c
  src/shim/preload_syscalls.c
  src/test/CMakeLists.txt
  src/test/signal/CMakeLists.txt
  src/test/signal/signal.test.shadow.config.yaml
  src/test/signal/test_signal.c
  src/test/unistd/test_unistd.rs
Labels: Component: Main, Type: Enhancement

#1090 Avoid logging in the shim until we have a set a logger
  src/main/shmem/shmem_cleanup.c
  src/shim/shim.c
  src/support/logger/logger.c
Labels: Component: Libraries, Type: Bug

#1095 Test C syscall handlers in CI
  .github/workflows/run_tests.yml
  CMakeLists.txt
  ci/container_scripts/build_and_install.sh
  src/test/pipe/test_pipe.rs
Labels: Component: Testing, Priority: Low, Type: Maintenance

#1096 Minor fix for Rust compiler warning
  src/main/host/descriptor/mod.rs
Labels: Component: Main, Priority: Low, Type: Maintenance

#1098 Simplify preloaded function list
  src/shim/CMakeLists.txt
  src/shim/preload_libraries.c
  src/shim/preload_syscall.c
  src/shim/preload_syscalls.c
Labels: Component: Libraries, Type: Maintenance

#1100 Pin CPUs in phold test for efficiency
  src/test/phold/CMakeLists.txt
Labels: Component: Testing, Type: Maintenance

#1099 Remove stale gitignore entries, add new entries and comments
  .gitignore
  src/main/Cargo.lock
  src/test/Cargo.lock
Labels: Component: Tools, Type: Maintenance

#1109 Updated Cargo lock file
  src/main/Cargo.lock
Labels: Component: Build, Type: Maintenance

#1102 Fix tcp test
  src/shim/preload_syscall.c
  src/test/tcp/CMakeLists.txt
  src/test/tcp/test_tcp.c
Labels: Component: Testing, Type: Bug

#1110 Add some determinism fixes and re-enable tests
  src/main/bindings/rust/wrapper.rs
  src/main/host/descriptor/file.c
  src/main/host/syscall/unistd.c
  src/main/host/syscall/unistd.h
  src/main/host/syscall_handler.c
  src/shim/preload_libraries.c
  src/shim/preload_syscall.c
  src/shim/preload_syscalls.c
  src/shim/shim_logger.c
  src/shim/shim_logger.h
  src/test/CMakeLists.txt
  src/test/determinism/CMakeLists.txt
  src/test/determinism/determinism1.test.shadow.config.yaml
  src/test/determinism/determinism1_compare.cmake
  src/test/determinism/determinism2.test.shadow.config.yaml
  src/test/determinism/determinism2_compare.cmake
  src/test/phold/test_phold.c
Labels: Component: Testing, Type: Enhancement

#1111 Adding missing syscalls, poll handler and tests
  src/main/CMakeLists.txt
  src/main/bindings/rust/wrapper.rs
  src/main/host/cpu.c
  src/main/host/descriptor/epoll.c
  src/main/host/descriptor/epoll.h
  src/main/host/descriptor/file.c
  src/main/host/descriptor/file.h
  src/main/host/process.c
  src/main/host/syscall/poll.c
  src/main/host/syscall/poll.h
  src/main/host/syscall/protected.h
  src/main/host/syscall_handler.c
  src/shim/preload_syscalls.c
  src/test/poll/CMakeLists.txt
  src/test/poll/test_poll.rs
  src/test/tcp/CMakeLists.txt
Labels: Component: Main, Type: Enhancement

#1114 Define macros for consistent & concise test defs
  src/test/CMakeLists.txt
  src/test/bind/CMakeLists.txt
  src/test/bind/bind-shadow.yaml
Labels: Component: Testing, Type: Maintenance

#1115 Support flushing log output using the logger interface
  src/main/core/logger/log_wrapper.rs
  src/main/core/logger/shadow_logger.c
  src/support/logger/logger.c
  src/support/logger/logger.h
  src/support/logger/rust_bindings/src/bindings.rs
Labels: Component: Libraries

#1116 Convert rust tests to use test macros
  src/main/host/syscall_handler.c
  src/test/CMakeLists.txt
  src/test/bindc/CMakeLists.txt
  src/test/bindc/bindc.yaml
  src/test/bindc/test_bind.c
  src/test/eventfd/CMakeLists.txt
  src/test/eventfd/eventfd.yaml
  src/test/ifaddrs/CMakeLists.txt
  src/test/ifaddrs/ifaddrs.yaml
  src/test/memory/CMakeLists.txt
  src/test/memory/mmap.yaml
  src/test/pipe/CMakeLists.txt
  src/test/pipe/pipe.yaml
  src/test/poll/CMakeLists.txt
  src/test/poll/poll.yaml
  src/test/pthreads/CMakeLists.txt
  src/test/pthreads/pthreads.yaml
  src/test/random/CMakeLists.txt
  src/test/random/random.yaml
  src/test/sleep/CMakeLists.txt
  src/test/sleep/sleep.yaml
  src/test/socket/CMakeLists.txt
  src/test/socket/accept/CMakeLists.txt
  src/test/socket/accept/accept.yaml
  src/test/socket/bind/CMakeLists.txt
  src/test/socket/bind/bind.yaml
  src/test/socket/connect/CMakeLists.txt
  src/test/socket/connect/connect.yaml
  src/test/socket/getpeername/CMakeLists.txt
  src/test/socket/getpeername/getpeername.yaml
  src/test/socket/getsockname/CMakeLists.txt
  src/test/socket/getsockname/getsockname.yaml
  src/test/socket/listen/CMakeLists.txt
  src/test/socket/listen/listen.yaml
  src/test/socket/sendto_recvfrom/CMakeLists.txt
  src/test/socket/sendto_recvfrom/sendto-recvfrom.shadow.config.xml
  src/test/socket/sendto_recvfrom/sendto-recvfrom.yaml
  src/test/socket/shutdown/CMakeLists.txt
  src/test/socket/shutdown/shutdown.yaml
  src/test/socket/socket/CMakeLists.txt
  src/test/socket/socket/socket.yaml
  src/test/socket/socketpair/CMakeLists.txt
  src/test/socket/socketpair/socketpair.yaml
  src/test/socket/sockopt/CMakeLists.txt
  src/test/socket/sockopt/sockopt.yaml
  src/test/unistd/CMakeLists.txt
  src/test/unistd/unistd.yaml
Labels: Component: Testing, Type: Maintenance

#1119 Rename interpose modes to hybrid, ptrace, and preload
  src/main/core/slave.c
  src/main/core/support/options.c
  src/main/core/support/options.h
  src/main/host/process.c
  src/shim/shim.c
  src/test/bindc/CMakeLists.txt
  src/test/clone/CMakeLists.txt
  src/test/config/read_from_stdin/CMakeLists.txt
  src/test/cpp/CMakeLists.txt
  src/test/epoll/CMakeLists.txt
  src/test/eventfd/CMakeLists.txt
  src/test/futex/CMakeLists.txt
  src/test/ifaddrs/CMakeLists.txt
  src/test/memory/CMakeLists.txt
  src/test/phold/CMakeLists.txt
  src/test/pipe/CMakeLists.txt
  src/test/poll/CMakeLists.txt
  src/test/pthreads/CMakeLists.txt
  src/test/random/CMakeLists.txt
  src/test/signal/CMakeLists.txt
  src/test/sleep/CMakeLists.txt
  src/test/sockbuf/CMakeLists.txt
  src/test/socket/accept/CMakeLists.txt
  src/test/socket/bind/CMakeLists.txt
  src/test/socket/connect/CMakeLists.txt
  src/test/socket/getpeername/CMakeLists.txt
  src/test/socket/getsockname/CMakeLists.txt
  src/test/socket/listen/CMakeLists.txt
  src/test/socket/sendto_recvfrom/CMakeLists.txt
  src/test/socket/shutdown/CMakeLists.txt
  src/test/socket/socket/CMakeLists.txt
  src/test/socket/socketpair/CMakeLists.txt
  src/test/socket/sockopt/CMakeLists.txt
  src/test/tcp/CMakeLists.txt
  src/test/udp/CMakeLists.txt
  src/test/unistd/CMakeLists.txt
Labels: Component: Main, Component: Testing, Type: Maintenance

#1124 Fix Rust pipe descriptor
  src/main/host/descriptor/pipe.rs
  src/main/utility/byte_queue.rs
Labels: Component: Main, Type: Bug

#1125 Added warning when debug logging enabled, but not built in debug mode
  src/main/core/main.c
Labels: Component: Main, Priority: Low, Type: Enhancement

#1126 Rust logger performance improvements
  src/main/Cargo.toml
  src/main/bindings/rust/CMakeLists.txt
  src/main/bindings/rust/wrapper.h
  src/main/bindings/rust/wrapper.rs
  src/main/core/logger/log_wrapper.rs
  src/main/core/logger/shadow_logger.c
  src/main/core/logger/shadow_logger.h
Labels: Component: Main, Priority: Low, Type: Enhancement

#1123 Update and extend the file tests and fix our file support
  src/main/host/descriptor/file.c
  src/main/host/descriptor/file.h
  src/main/host/syscall/mman.c
  src/shim/preload_libraries.c
  src/test/file/CMakeLists.txt
  src/test/file/file.yaml
  src/test/file/test_file.c
  src/test/memory/test_mmap.rs
Labels: Component: Testing, Type: Bug, Type: Maintenance
