Repository shadow/shadow, pull requests merged in 2021-06, with the labels that each got.

#1391 Raise fd limit to hard limit
  src/main/core/main.c
Labels: Component: Main, Type: Enhancement

#1385 More small documentation changes, and install cargo/rustc from rustup
  .github/workflows/lint.yml
  docs/README.md
  docs/developer_guide.md
  docs/install_dependencies.md
Labels: Component: Documentation, Type: Maintenance

#1386 Pass references explicitly instead of getting from global Worker
  src/main/bindings/c/bindings.h
  src/main/bindings/c/cbindgen-opaque.toml
  src/main/bindings/c/cbindgen.toml
  src/main/bindings/rust/CMakeLists.txt
  src/main/bindings/rust/wrapper.rs
  src/main/core/logger/shadow_logger.rs
  src/main/core/worker.c
  src/main/core/worker.h
  src/main/core/worker.rs
  src/main/host/context.rs
  src/main/host/host.rs
  src/main/host/memory_manager/memory_copier.rs
  src/main/host/memory_manager/memory_mapper.rs
  src/main/host/memory_manager/mod.rs
  src/main/host/mod.rs
  src/main/host/process.c
  src/main/host/process.h
  src/main/host/process.rs
  src/main/host/syscall/mman.c
  src/main/host/syscall/unistd.rs
  src/main/host/thread.c
  src/main/host/thread.h
  src/main/host/thread.rs
  src/main/host/thread_preload.c
  src/main/host/thread_protected.h
  src/main/host/thread_ptrace.c
Labels: Component: Main, Tag: Performance, Type: Maintenance

#1394 Fix simulation time in log messages
  src/main/core/support/simulation_time.rs
  src/main/core/worker.rs
Labels: Component: Main, Type: Bug

#1393 Remove C usage of getActiveHost, getActiveProcess, getActiveThread
  src/main/bindings/rust/wrapper.rs
  src/main/core/work/event.c
  src/main/core/work/task.c
  src/main/core/work/task.h
  src/main/core/worker.c
  src/main/core/worker.h
  src/main/host/descriptor/channel.c
  src/main/host/descriptor/compat_socket.c
  src/main/host/descriptor/compat_socket.h
  src/main/host/descriptor/descriptor.c
  src/main/host/descriptor/descriptor.h
  src/main/host/descriptor/descriptor_types.h
  src/main/host/descriptor/epoll.c
  src/main/host/descriptor/eventd.c
  src/main/host/descriptor/file.c
  src/main/host/descriptor/file.h
  src/main/host/descriptor/socket.c
  src/main/host/descriptor/socket.h
  src/main/host/descriptor/tcp.c
  src/main/host/descriptor/tcp.h
  src/main/host/descriptor/timer.c
  src/main/host/descriptor/timer.h
  src/main/host/descriptor/transport.c
  src/main/host/descriptor/transport.h
  src/main/host/descriptor/udp.c
  src/main/host/descriptor/udp.h
  src/main/host/host.c
  src/main/host/network_interface.c
  src/main/host/network_interface.h
  src/main/host/process.c
  src/main/host/syscall/file.c
  src/main/host/syscall/fileat.c
  src/main/host/syscall/protected.c
  src/main/host/syscall/socket.c
  src/main/host/syscall/timerfd.c
  src/main/host/syscall/uio.c
  src/main/host/syscall/unistd.c
  src/main/host/syscall_condition.c
  src/main/host/thread.c
  src/main/host/thread.h
  src/main/host/tracker.c
  src/main/host/tracker.h
  src/main/routing/packet.c
  src/main/routing/packet.h
  src/main/routing/packet.minimal.h
  src/main/routing/payload.c
  src/main/routing/payload.h
  src/main/routing/router.c
  src/main/routing/router.h
  src/main/utility/pcap_writer.c
  src/main/utility/pcap_writer.h
Labels: Component: Main, Type: Maintenance

#1395 test_clone: Fix and extend clone_child_exits_after_leader
  src/test/clone/CMakeLists.txt
  src/test/clone/clone-nomm.yaml
  src/test/clone/test_clone.c
Labels: Component: Testing, Type: Bug

#1401 Fix and document build errors on CentOS 8
  ci/container_scripts/install_deps.sh
  docs/install_dependencies.md
Labels: Component: Build, Component: Documentation, Type: Bug

#1400 Removed unnecessary files from installation
  CMakeLists.txt
  resource/CMakeLists.txt
Labels: Component: Build

#1397 Updated and reorganized 'getting_started.md'
  CMakeLists.txt
  docs/getting_started.md
  docs/log_format.md
  docs/parsing_statistics.md
  resource/CMakeLists.txt
  resource/examples/shadow.config.xml
  resource/examples/tgen.client.graphml.xml
  resource/examples/tgen.server.graphml.xml
  resource/topology.graphml.xml.xz
Labels: Component: Documentation, Type: Enhancement

#1402 Updates to log format, readme, and installation docs
  README.md
  docs/README.md
  docs/install_shadow.md
  docs/log_format.md
Labels: Component: Documentation, Type: Maintenance

#1403 Updated configuration docs and added 1.x -> 2.x migration doc
  docs/README.md
  docs/getting_started.md
  docs/log_format.md
  docs/migrating_from_1x.md
  docs/network_config.md
  docs/network_graph_attributes.md
  docs/parsing_statistics.md
  docs/shadow_config.md
  docs/shadow_config_options.md
Labels: Component: Documentation, Type: Enhancement

#1406 Updated example in 'parsing_statistics' doc
  docs/parsing_statistics.md
  src/tools/plot-shadow.py
Labels: Component: Documentation, Type: Maintenance

#1405 Removed cpack configuration
  CMakeLists.txt
  cpack/CMakeLists.txt
  cpack/CPackConfig.cmake
  cpack/PackageDescription.txt
Labels: Component: Build, Type: Maintenance

#1404 Change install prefix to '~/.local'
  .github/workflows/run_tor.yml
  Dockerfile
  README.md
  docs/developer_guide.md
  docs/getting_started.md
  docs/install_shadow.md
  setup
  src/test/tor/minimal/CMakeLists.txt
  src/test/tor/minimal/tor-minimal.yaml
  src/tools/generate_example_config.py
Labels: Component: Build, Type: Maintenance

#1411 Reorganize tor config files in tor minimal test
  src/test/tor/minimal/conf/tor.authority.torrc
  src/test/tor/minimal/conf/tor.common.torrc
  src/test/tor/minimal/conf/tor.exit.torrc
  src/test/tor/minimal/conf/tor.hiddenserver.torrc
  src/test/tor/minimal/conf/tor.non-exit.torrc
  src/test/tor/minimal/conf/tor.relay.torrc
  src/test/tor/minimal/shadow.data.template/hosts/4uthority/torrc
  src/test/tor/minimal/shadow.data.template/hosts/4uthority/torrc-defaults
  src/test/tor/minimal/shadow.data.template/hosts/exit1/torrc
  src/test/tor/minimal/shadow.data.template/hosts/exit1/torrc-defaults
  src/test/tor/minimal/shadow.data.template/hosts/exit2/torrc
  src/test/tor/minimal/shadow.data.template/hosts/exit2/torrc-defaults
  src/test/tor/minimal/shadow.data.template/hosts/hiddenserver/torrc
  src/test/tor/minimal/shadow.data.template/hosts/hiddenserver/torrc-defaults
  src/test/tor/minimal/shadow.data.template/hosts/relay1/torrc
  src/test/tor/minimal/shadow.data.template/hosts/relay1/torrc-defaults
  src/test/tor/minimal/shadow.data.template/hosts/relay2/torrc
  src/test/tor/minimal/shadow.data.template/hosts/relay2/torrc-defaults
  src/test/tor/minimal/shadow.data.template/hosts/torbridgeclient/torrc
  src/test/tor/minimal/shadow.data.template/hosts/torbridgeclient/torrc-defaults
  src/test/tor/minimal/shadow.data.template/hosts/torclient/torrc
  src/test/tor/minimal/shadow.data.template/hosts/torclient/torrc-defaults
  src/test/tor/minimal/shadow.data.template/hosts/torhiddenclient/torrc
  src/test/tor/minimal/shadow.data.template/hosts/torhiddenclient/torrc-defaults
  src/test/tor/minimal/tor-minimal.yaml
Labels: Component: Testing, Type: Maintenance

#1407 Add units to topology latency
  docs/network_graph_attributes.md
  docs/parsing_statistics.md
  src/main/bindings/c/bindings.h
  src/main/core/support/configuration.rs
  src/main/core/support/units.rs
  src/main/routing/topology.c
  src/test/config/convert/shadow.expected.yaml
  src/test/config/convert/topology.expected.gml
  src/test/determinism/determinism1.test.shadow.config.yaml
  src/test/determinism/determinism2.test.shadow.config.yaml
  src/test/phold/phold.yaml
  src/test/tcp/tcp-blocking-loopback.yaml
  src/test/tcp/tcp-blocking-lossless.yaml
  src/test/tcp/tcp-blocking-lossy.yaml
  src/test/tcp/tcp-iov-loopback.yaml
  src/test/tcp/tcp-iov-lossless.yaml
  src/test/tcp/tcp-iov-lossy.yaml
  src/test/tcp/tcp-nonblocking-epoll-loopback.yaml
  src/test/tcp/tcp-nonblocking-epoll-lossless.yaml
  src/test/tcp/tcp-nonblocking-epoll-lossy.yaml
  src/test/tcp/tcp-nonblocking-poll-loopback.yaml
  src/test/tcp/tcp-nonblocking-poll-lossless.yaml
  src/test/tcp/tcp-nonblocking-poll-lossy.yaml
  src/test/tcp/tcp-nonblocking-select-loopback.yaml
  src/test/tcp/tcp-nonblocking-select-lossless.yaml
  src/test/tcp/tcp-nonblocking-select-lossy.yaml
  src/test/tor/minimal/tor-minimal.yaml
  src/tools/convert_legacy_topology.py
Labels: Component: Main, Type: Enhancement

#1416 Accept microseconds in the topology latency
  src/main/bindings/c/bindings.h
  src/main/core/support/units.rs
  src/main/routing/topology.c
Labels: Component: Main, Type: Enhancement

#1418 Change topology jitter from float to string
  docs/network_graph_attributes.md
  src/main/routing/topology.c
  src/test/tor/minimal/tor-minimal.yaml
Labels: Component: Main, Type: Maintenance

#1417 Plugin -> Managed Process
  docs/developer_guide.md
  docs/migrating_from_1x.md
  docs/nsf_sponsorship.md
  docs/shadow_config_options.md
  docs/using_recompiled_libc.md
Labels: Component: Documentation

#1420 Add CI lint to check Shadow version in Cargo lockfile
  .github/workflows/lint.yml
  docs/maintainer_playbook.md
Labels: Component: Testing, Component: Tools, Type: Enhancement

#1427 Small changes to quantity/unit parsing, and added section to shadow config docs
  docs/shadow_config.md
  src/main/core/support/units.rs
Labels: Component: Documentation, Type: Enhancement

#1419 Handle unaligned pointers from managed processes gracefully
  src/main/host/memory_manager/memory_mapper.rs
  src/main/host/memory_manager/mod.rs
  src/main/host/syscall/unistd.rs
  src/main/host/syscall_types.rs
  src/test/Cargo.toml
  src/test/memory/CMakeLists.txt
  src/test/memory/test_unaligned.rs
  src/test/memory/unaligned.yaml
Labels: Component: Main, Type: Enhancement

#1428 Fix docs to properly update the git tag after bumpversion
  docs/maintainer_playbook.md
Labels: Component: Documentation, Type: Maintenance

#1436 Formatting changes to docs
  README.md
  docs/ci.md
  docs/coding_style.md
  docs/contributing.md
  docs/developer_guide.md
  docs/install_dependencies.md
  docs/install_shadow_with_docker.md
  docs/maintainer_playbook.md
  docs/migrating_from_1x.md
  docs/network_graph_overview.md
  docs/network_graph_spec.md
  docs/pull_requests.md
  docs/shadow_config_overview.md
  docs/shadow_config_spec.md
  docs/supported_platforms.md
  docs/system_configuration.md
Labels: Component: Documentation, Type: Maintenance

#1438 Minor updates to top-level readme
  README.md
Labels: Component: Documentation

#1442 Update dev branch refs to ref main instead
  .github/dependabot.yml
  .github/workflows/coverage.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  .github/workflows/run_tests.yml
  .github/workflows/run_tor.yml
  README.md
  codecov.yml
  docs/developer_guide.md
  docs/using_recompiled_libc.md
Labels: Component: Build, Component: Documentation, Type: Maintenance

#1447 Minor wording tweaks to readme
  README.md
Labels: Component: Documentation

#1448 Update rust dependencies
  src/main/Cargo.lock
  src/test/Cargo.lock
Labels: Component: Build, Type: Maintenance

#1463 Auto assign author and labels to pull requests
  .github/pr_labeler_conf.yml
  .github/workflows/pr_metadata.yml
Labels: Component: Tools

#1458 Conveniently run the tor test manually
  docs/getting_started_tor.md
  src/test/tor/minimal/conf/tor.client.torrc
  src/test/tor/minimal/run.sh
  src/test/tor/minimal/verify.sh
Labels: Component: Testing, Type: Maintenance

#1466 Fixed github labeler config
  .github/pr_labeler_conf.yml
Labels: Type: Bug

#1465 Updated tor minimal test hs to v3
  src/test/tor/minimal/conf/tgen.torhiddenclient.graphml.xml
  src/test/tor/minimal/shadow.data.template/hosts/hiddenserver/hs/hostname
  src/test/tor/minimal/shadow.data.template/hosts/hiddenserver/hs/hs_ed25519_public_key
  src/test/tor/minimal/shadow.data.template/hosts/hiddenserver/hs/hs_ed25519_secret_key
  src/test/tor/minimal/shadow.data.template/hosts/hiddenserver/hs/private_key
Labels: Component: Testing, Type: Enhancement

#1467 Copied '1_gbit_switch' graph to docs
  docs/shadow_config_spec.md
  src/main/core/support/configuration.rs
Labels: Component: Documentation

#1471 seccomp: Disable Speculative Store Bypass mitigation
  src/lib/shim/shim.c
Labels: Component: Libraries, Component: Testing

#1470 Handle FUTEX_BITSET_MATCH_ANY case of futex bitset ops
  src/main/host/syscall/futex.c
  src/main/host/syscall/poll.c
  src/main/host/syscall/protected.c
  src/main/host/syscall/protected.h
  src/main/host/syscall/time.c
  src/main/host/syscall_handler.c
  src/test/futex/test_futex.c
Labels: Component: Main, Component: Testing

#1472 Update labeler rule for testing label
  .github/pr_labeler_conf.yml
Labels: Component: Testing

#1474 Updated PR labeler config
  .github/pr_labeler_conf.yml
Labels: Component: Tools, Type: Bug

#1477 _vshadow_raw_syscall: ensure new stack is aligned
  src/lib/shim/preload_syscall.c
Labels: Component: Libraries, Type: Bug

#1479 process_free: don't try to write back pointers to dead process
  src/main/host/process.c
Labels: Component: Main, Type: Bug

#1480 MemoryManager: Fix log messages and returned errors
  src/main/host/memory_manager/mod.rs
Labels: Component: Main, Type: Bug

#1460 Some determinism fixes
  README.md
  src/main/core/support/configuration.rs
  src/main/host/descriptor/epoll.c
  src/main/host/descriptor/tcp.c
  src/test/determinism/CMakeLists.txt
  src/test/determinism/determinism2_compare.cmake
Labels: Component: Main, Type: Bug

#1478 signal syscalls: handle variable sized signal sets
  src/main/host/syscall/signal.c
Labels: Component: Main, Type: Bug

#1483 Unref partial packet during tcp free
  src/main/host/descriptor/tcp.c
Labels: Component: Main, Type: Bug

#1486 Drop support for centos 7
  .github/workflows/run_tests.yml
  ci/container_scripts/install_deps.sh
  ci/container_scripts/install_extra_deps.sh
  ci/run.sh
  docs/README.md
  docs/install_dependencies.md
  docs/supported_platforms.md
  docs/using_recompiled_libc.md
  src/main/CMakeLists.txt
  src/main/core/scheduler/scheduler_policy_host_steal.c
  src/main/host/thread_ptrace.c
  src/main/host/tsc.c
  src/main/shmem/shmem_cleanup.c
  src/test/socket/sendto_recvfrom/CMakeLists.txt
Labels: Component: Build, Component: Documentation, Component: Main, Component: Testing

#1482 Remove (broken) support for old signal APIs
  src/main/host/syscall/signal.c
  src/main/host/syscall/signal.h
  src/main/host/syscall_handler.c
Labels: Component: Main

#1487 Ensure thread is really dead before notifying other threads that it is
  src/main/host/process.c
Labels: Component: Main

#1469 Custom semaphore implementation
  src/lib/shim/CMakeLists.txt
  src/lib/shim/binary_spinning_sem.cc
  src/lib/shim/binary_spinning_sem.h
  src/lib/shim/shadow_sem.c
  src/lib/shim/shadow_sem.h
  src/lib/shim/shim.c
  src/main/host/thread_preload.c
Labels: Component: Build, Component: Libraries, Component: Main

#1488 Harden clone
  src/main/host/syscall/futex.c
  src/test/clone/test_clone.c
Labels: Component: Main, Component: Testing
