Repository shadow/shadow, pull requests merged in 2023-07, with the labels that each got.

#3063 Create a specialized hash table for the shim's TLS
  .github/workflows/sanitizers.yml
  src/Cargo.lock
  src/lib/vasi-sync/Cargo.toml
  src/lib/vasi-sync/src/atomic_tls_map.rs
  src/lib/vasi-sync/src/lib.rs
  src/lib/vasi-sync/src/sync.rs
  src/lib/vasi-sync/tests/atomic-tls-map-tests.rs
Labels: Component: Libraries, Component: Testing, Component: Build

#3066 Shim: Move shared memory objects into Rust
  src/lib/shim/shim.c
  src/lib/shim/src/lib.rs
  src/lib/shim/src/shimlogger.rs
Labels: Component: Libraries

#3064 Shim TLS improvements
  src/lib/linux-api/src/exit.rs
  src/lib/linux-api/src/lib.rs
  src/lib/shim/build.rs
  src/lib/shim/shim_syscall.c
  src/lib/shim/shim_tls.c
  src/lib/shim/shim_tls.h
  src/lib/shim/src/lib.rs
  src/lib/shim/src/mmap_box.rs
  src/lib/shim/src/tls.rs
  src/lib/vasi-sync/src/atomic_tls_map.rs
  src/lib/vasi-sync/src/lazy_lock.rs
  src/lib/vasi-sync/src/sync.rs
  src/lib/vasi-sync/tests/lazylock-tests.rs
  src/main/host/descriptor/regular_file.c
  src/test/golang/CMakeLists.txt
Labels: Component: Libraries, Component: Testing, Component: Main, Component: Build

#3070 Add `deny(unsafe_op_in_unsafe_fn)` to all libs
  src/lib/formatting-nostd/src/lib.rs
  src/lib/gml-parser/src/lib.rs
  src/lib/log-c2rust/src/lib.rs
  src/lib/logger/src/lib.rs
  src/lib/pod/src/lib.rs
  src/lib/shadow-build-common/src/lib.rs
  src/lib/shim/src/lib.rs
  src/lib/std-util/src/lib.rs
  src/lib/syscall-logger/src/lib.rs
  src/lib/tsc/src/lib.rs
  src/lib/vasi-macro/src/lib.rs
  src/lib/vasi/src/lib.rs
Labels: Component: Libraries

#3069 Convert shim signal handling to Rust
  src/lib/linux-api/build.rs
  src/lib/linux-api/src/signal.rs
  src/lib/shadow-shim-helper-rs/src/shim_shmem.rs
  src/lib/shim/build.rs
  src/lib/shim/shim.c
  src/lib/shim/shim_rdtsc.c
  src/lib/shim/shim_signals.c
  src/lib/shim/shim_signals.h
  src/lib/shim/shim_syscall.c
  src/lib/shim/shim_syscall.h
  src/lib/shim/src/lib.rs
  src/lib/shim/src/signals.rs
  src/main/host/syscall/signal.c
Labels: Component: Libraries, Component: Main

#3071 Fix and reenable clone tests
  src/Cargo.toml
  src/lib/shim/src/tls.rs
  src/test/clone/CMakeLists.txt
Labels: Component: Libraries, Component: Testing, Component: Build

#3074 Bump rustix from 0.37 to 0.38
  src/Cargo.lock
  src/lib/formatting-nostd/Cargo.toml
  src/lib/formatting-nostd/src/borrowed_fd_writer.rs
  src/lib/linux-api/Cargo.toml
  src/lib/shim/Cargo.toml
  src/lib/vasi-sync/Cargo.toml
Labels: Component: Libraries, Component: Build

#3073 Rework Rust version pinning
  .dockerignore
  .github/workflows/ci_maintenance.yml
  .github/workflows/lint.yml
  .github/workflows/sanitizers.yml
  .gitignore
  ci/container_scripts/install_extra_deps.sh
  ci/rust-toolchain-nightly.toml
  ci/rust-toolchain-stable.toml
  docs/install_dependencies.md
Labels: Component: Testing, Component: Documentation

#3075 Remove syscall shadow_get_shm_blk
  src/main/host/syscall/shadow.c
  src/main/host/syscall/shadow.h
  src/main/host/syscall_handler.c
  src/main/host/syscall_numbers.h
Labels: Component: Main

#3076 Updates to rust builds
  src/CMakeLists.txt
Labels: Component: Build

#3078 simple_latch tests: increase test timing threshold
  src/main/utility/synchronization/simple_latch.rs
Labels: Component: Main

#3077 Migrate shim clone code to Rust and make some improvements
  src/lib/shadow-shim-helper-rs/build.rs
  src/lib/shadow-shim-helper-rs/shadow_sem.c
  src/lib/shadow-shim-helper-rs/shadow_sem.h
  src/lib/shadow-shim-helper-rs/shadow_spinlock.c
  src/lib/shadow-shim-helper-rs/shadow_spinlock.h
  src/lib/shadow-shim-helper-rs/src/shim_event.rs
  src/lib/shadow-shim-helper-rs/src/syscall_types.rs
  src/lib/shim/shim.c
  src/lib/shim/shim.h
  src/lib/shim/shim_syscall.c
  src/lib/shim/src/clone.rs
  src/lib/shim/src/lib.rs
  src/main/host/managed_thread.rs
Labels: Component: Libraries, Component: Main

#3081 Remove last remaining C references to shmem allocator
  src/Cargo.lock
  src/lib/shadow-shim-helper-rs/build.rs
  src/lib/shadow-shim-helper-rs/src/ipc.rs
  src/lib/shadow-shim-helper-rs/src/shim_event.rs
  src/lib/shadow-shim-helper-rs/src/shim_shmem.rs
  src/lib/shim/Cargo.toml
  src/lib/shim/build.rs
  src/lib/shim/shim.c
  src/lib/shim/shim.h
  src/lib/shim/shim_sys.c
  src/lib/shim/shim_syscall.c
  src/lib/shim/src/clone.rs
  src/lib/shim/src/lib.rs
  src/lib/shim/src/signals.rs
  src/lib/shim/src/syscall.rs
  src/main/host/syscall/shadow.c
Labels: Component: Libraries, Component: Main, Component: Build

#3080 Extra tests workflow: tweaks to sccache
  .github/workflows/extra_tests.yml
Labels: Component: Testing
