Repository shadow/shadow, pull requests merged in 2025-04, with the labels that each got.

#3556 Fix clippy warnings with new rust version, and upgrade rust version in CI
  CHANGELOG.md
  ci/rust-toolchain-nightly.toml
  ci/rust-toolchain-stable.toml
  src/lib/vasi-sync/src/scmutex.rs
  src/main/core/work/task.rs
  src/main/host/process.rs
  src/main/network/relay/mod.rs
  src/main/utility/byte_queue.rs
  src/main/utility/shm_cleanup.rs
  src/test/environment/test_env.rs
  src/test/test_utils.rs
Labels: Component: Libraries, Type: Maintenance, Component: Testing, Component: Main, Component: Documentation

#3554 Fix the test for getauxval when the type is not found
  src/lib/shim/src/reinit_auxvec_random.rs
Labels: Component: Libraries, Component: Testing

#3560 getauxval test: a few robustness tweaks
  src/lib/shim/src/reinit_auxvec_random.rs
Labels: Component: Libraries, Component: Testing

#3566 Run 'cargo update'
  src/Cargo.lock
  src/test/socket/socket/test_socket.rs
Labels: Component: Testing, Component: Build

#3562 Fix packet order of FIN from `SHUT_WR`
  CHANGELOG.md
  src/main/host/descriptor/tcp.c
  src/test/regression/3100/CMakeLists.txt
  src/test/regression/3100/regression-3100.yaml
  src/test/regression/CMakeLists.txt
Labels: Component: Testing, Component: Main, Component: Build, Component: Documentation

#3570 Add another regression test for issue 3100
  CHANGELOG.md
  src/test/regression/3100/CMakeLists.txt
  src/test/regression/3100/regression-3100-a.yaml
  src/test/regression/3100/regression-3100-b.yaml
Labels: Component: Testing, Component: Build, Component: Documentation

#3574 test EOF behavior and fix missing EPOLLRDHUP events for TCP sockets
  CHANGELOG.md
  src/main/host/descriptor/epoll/entry.rs
  src/main/host/descriptor/mod.rs
  src/main/host/descriptor/tcp.c
  src/test/epoll/epoll-rs.yaml
  src/test/epoll/test_epoll.rs
Labels: Component: Testing, Component: Main, Component: Documentation
